### ISSUE TITLE
Use a fixed Merge Strategy for apiPrefix file

### ISSUE THREAD

**Issue by KPull** [Ejja-Ha-Nieklu/ejja-ha-nieklu#30]
We can specify a deployment branch and a development branch with different configuration files. Then, in the deployment branch, the apiPrefix file contains the correct production server endpoint URL. We also mark the file to use an 'ours' merge strategy so each time we merge from a development branch, git automatically fixes the conflict using the URL on the deployment branch.

More information about Git attributes:
https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#Merge-Strategies

**Comment by camilleriluke** [comment]
+1

I was thinking about this few days ago, it would a good idea also to set up a staging server (which might also run a staging branch)

**Comment by KPull** [comment]
Resolved using the different deployment types.
