### ISSUE TITLE
Mark as paid

### ISSUE THREAD

**Issue by camilleriluke** [Ejja-Ha-Nieklu/ejja-ha-nieklu#5]
This will help order authors to keep track of who paid before the order was printed.

* ~~Checkbox near each item in the order~~ (implemented)
* State should be persisted only on local storage (no need to share it with everyone, since the person opening the order will be collecting the money)
* On checkbox tick mark item as strikethrough
* Strikethrough in print view might not be the best option (might be unreadable) - we need to figure out a better way to depict this in the print view.

**Comment by KPull** [comment]
I think we can close this now.
